web-server/apps/jobs/urls.py
from django.urls import include, path
from jobs.views import JobsListView, JobDetailView, CreateContainerView, ContainerDetailView, UploadContainerView

import debug_toolbar

app_name = 'jobs'

urlpatterns = [

    path('', JobsListView.as_view(), name='index'),
    path('__debug__/', include(debug_toolbar.urls)),
    path('<job_id>/', JobDetailView.as_view(), name='job-detail'),
    path('get-container/<uid>/', ContainerDetailView.as_view(), name='container-detail'),
    path('create-container/<job_id>/', CreateContainerView.as_view(), name='create-container'),
    path('upload-container/<uid>/', UploadContainerView.as_view(), name='upload-container'),

]

web-server/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import debug_toolbar


urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls', namespace='jobs')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="{{LANGUAGE_CODE}}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

</head>
<body>
<div>
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock %}
    <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5" role="main">
        {% block content %}
        {% endblock content %}
    </main>
</div>
    {% block footer %}
        {% include 'footer.html' %}
    {% endblock %}

    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

templates/footer.html
<!-- <nav class="navbar fixed-bottom navbar-light bg-light">
  <div class='col-12'>
    <div class="float-right">your ad could be here</div>
  </div>
</nav> -->

templates/navbar.html
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'jobs:index'%}">
    citar
  </a>
</nav>