web-server/apps/jobs/urls.py
from django.urls import include, path
from jobs.views import JobsListView, JobDetailView, CreateContainerView, ContainerDetailView, UploadContainerView

import debug_toolbar

app_name = 'jobs'

urlpatterns = [

    path('', JobsListView.as_view(), name='index'),
    path('__debug__/', include(debug_toolbar.urls)),
    path('<job_id>/', JobDetailView.as_view(), name='job-detail'),
    path('get-container/<uid>/', ContainerDetailView.as_view(), name='container-detail'),
    path('create-container/<job_id>/', CreateContainerView.as_view(), name='create-container'),
    path('upload-container/<uid>/', UploadContainerView.as_view(), name='upload-container'),

]

web-server/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import debug_toolbar


urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls', namespace='jobs')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web-server/apps/jobs/models.py
from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import JSONField

from libraries.models import Library

class Jobs(models.Model):
    data = JSONField(blank=True, null=True)  # This field type is a guess.
    job_id = models.IntegerField(unique=True, blank=True, null=True)
    libraries = models.TextField(blank=True, null=True, default='')
    command = models.TextField(blank=True, null=True, default='')

    class Meta:
        db_table = 'jobs'

    def __str__(self):
        return '{}'.format(self.job_id)

    def __unicode__(self):
        return '{}'.format(self.job_id)


class Statuses(models.Model):
    name = models.CharField(unique=True, max_length=50, blank=True, null=True)
    description = models.CharField(max_length=300, blank=True, null=True)

    class Meta:
        db_table = 'statuses'

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class ContainerCreationTask(models.Model):
    uid = models.CharField(max_length=100, null=True, blank=True, unique=True)
    job = models.ForeignKey('Jobs', on_delete=models.CASCADE)
    created = models.DateTimeField()
    modified = models.DateTimeField()
    libs = models.ManyToManyField(Library)
    status = models.ForeignKey('Statuses', models.DO_NOTHING, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    container_url = models.CharField(max_length=200, blank=True, null=True)
    container_type = models.CharField(max_length=1, default='0')

    @property
    def ready(self):
        if self.status.name == "created":
            return True
        return False

    @property
    def upload(self):
        if self.container_type == "2":
            return True
        return False

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(ContainerCreationTask, self).save(*args, **kwargs)

    class Meta:
        ## FIXME: change to container
        db_table = 'container_history'

    def __str__(self):
        return '{}'.format(self.uid)

    def __unicode__(self):
        return '{}'.format(self.uid)

web-server/apps/jobs/forms.py
from django import forms

from .models import ContainerCreationTask, Jobs
from libraries.models import Library

class CreateContainerForm(forms.ModelForm):
    CONTAINER_TYPE_CHOICES = (
        (1, 'Docker'),
        (2, 'Singularity'),
        # (0, 'RunC'),
    )

    # email = forms.EmailField(help_text='A valid email address, please.')
    container_type = forms.ChoiceField(choices=CONTAINER_TYPE_CHOICES)
    job_id = forms.CharField(widget=forms.HiddenInput)
    uid = forms.CharField(widget=forms.HiddenInput)

    class Meta:
        model = ContainerCreationTask
        fields = ('email', 'container_type', 'job_id', 'uid', 'libs')

    def __init__(self, *args, **kwargs):
        super(CreateContainerForm, self).__init__(*args, **kwargs)
        self.fields['libs'].queryset = Library.objects.filter(status=1)


class ImportContainerForm(forms.Form):
    image_name = forms.CharField(initial='', required=False)
    runtime_type = forms.CharField(initial='singularity')
    process_args = forms.CharField(initial='ls')
    process_env = forms.CharField(initial='', required=False)
    input_folder = forms.CharField(initial='/input')
    output_folder = forms.CharField(initial='/output')
    image_type = forms.CharField(initial='simg')

    author = forms.CharField(initial='ku')
    description = forms.CharField(initial='test_descr')
    title = forms.CharField(initial='test_title')

web-server/apps/jobs/views.py
import uuid
import requests

from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views.generic import DetailView, FormView, ListView, View
from django.shortcuts import render, redirect

from .models import Jobs, ContainerCreationTask, Statuses
from .forms import CreateContainerForm, ImportContainerForm

from libraries.models import Library

class JobsListView(ListView):
    """View for list with all jobs history."""
    model = Jobs
    paginate_by = 100  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class JobDetailView(DetailView):
    """View for job's detail. Can be obtain by job_id."""
    model = Jobs
    slug_url_kwarg = 'job_id'
    slug_field = 'job_id'

    template_name = 'jobs/jobs_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        s1 = context.get('object').libraries.replace(']','').replace('[','')
        libs = s1.replace('"','').split(",")

        new_libs = {}
        for el in libs:
            name = el.split('/')[1]
            version = el.split('/')[2]
            category = el.split('/')[0]
            lib = Library.objects.filter(name=name, version=version)
            if lib:
                status = lib.first().status
            else:
                status = 'not available'
            new_libs[el] = status

        context.get('object').libraries = new_libs
        context['containers'] = ContainerCreationTask.objects.filter(job__job_id = context.get('object').job_id).order_by('-created')
        return context


class CreateContainerView(FormView):
    """
    Form view for creation container. Use for check container type,
    user's email (for notification) etc.
    """
    model = Jobs

    form_class = CreateContainerForm
    template_name = 'jobs/form.html'
    success_url = '/test/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        s1 = Jobs.objects.get(job_id = self.kwargs['job_id']).libraries.replace(']','').replace('[','')

        # libs = s1.replace('"','').split(",")
        #
        new_libs = []
        # for el in libs:
        #     name = el.split('/')[1]
        #     version = el.split('/')[2]
        #     category = el.split('/')[0]
        #     lib = Library.objects.filter(name=name, version=version, status=1)
        #     if lib:
        #         print(lib)
        #         new_libs.append(el)
        #
        # context['libraries'] = new_libs
        return context

    def get_initial(self):
        initial = super().get_initial()
        initial['job_id'] = self.kwargs['job_id']
        initial['uid'] = str(uuid.uuid4())
        return initial

    def form_invalid(self, form):
        return super().form_invalid(form)

    def form_valid(self, form):
        temp = ContainerCreationTask(job = Jobs.objects.get(job_id = form.cleaned_data.get('job_id','')),
                                     uid=form.cleaned_data.get('uid',''),
                                     status=Statuses.objects.get(id=1),
                                     email=form.cleaned_data.get('email',''),
                                     container_type=form.cleaned_data.get('container_type','0'))
        temp.save()
        for el in form.cleaned_data['libs']:
            temp.libs.add(el)
        temp.save()
        data = {"uid": form.cleaned_data.get('uid','')}
        r = requests.post('http://134.60.152.82/restapi/create-container/', data=data)

        if r.status_code == 200:
            return HttpResponseRedirect(reverse('jobs:job-detail', kwargs={'job_id': self.kwargs['job_id']}))
        else:
            raise Http404

class ContainerDetailView(DetailView):
    """View for container's detail. Can be obtain by uid."""
    model = ContainerCreationTask
    slug_url_kwarg = 'uid'
    slug_field = 'uid'

    template_name = 'jobs/container_detail.html'


class UploadContainerView(FormView):
    """Send request for uploading container to EAAS server."""
    form_class = ImportContainerForm
    template_name = 'jobs/import_form.html'

    def form_valid(self, form):
        import json
        data = {"uid": self.kwargs['uid']}
        data.update(form.cleaned_data)
        r = requests.post('http://134.60.152.82/restapi/export-container/', data=data)

        if r.status_code == 200:
            return HttpResponseRedirect(reverse('jobs:container-detail', kwargs={'uid': self.kwargs['uid']}))
        else:
            raise Http404

templates/jobs/container_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <p>{{ object.job }}</p>
      <p>{{ object.status }}</p>
      {% if object.ready %}
        <p><a type="button" class="btn btn-outline-primary" href="/restapi/download-container/{{ object.uid }}">download</a></p>

      {% endif%}
      {% if object.ready and object.upload %}
        <p><a href='{% url "jobs:upload-container" object.uid %}' type="button" class="btn btn-primary btn-sm">upload to EAAS</a></p>
      {% endif%}
    </div>
  </div>
</div>
{% endblock%}

templates/jobs/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <form method="POST" class="col-sm-4" action="">
        {% csrf_token %}
        {{ form | crispy }}
        <!--
        {% for el in libraries %}
        <p>{{el}} <input class='libs' type="checkbox" id="{{el}}"></p>
        {% endfor %} -->
        <input type="submit" value="Submit" id="button">
      </form>
    </div>
  </div>
</div>
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

{% endblock%}

templates/jobs/import_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <form method="POST" class="col-sm-4" action="">
          {% csrf_token %}
          {{ form | crispy }}
          <input type="submit" value="Submit" id="button">
      </form>
    </div>
  </div>
</div>
{% endblock%}

templates/jobs/jobs_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
          <h1>{{ object.job_id }}</h1>
              <p>{{ object.status.name }}</p>
          <b>Meta-data</b>
          <div class="col-offset-4 col-8">{{ object.data }}</div><br>
          <b>Libraries</b>
          <div class="col-offset-4 col-8">
            {% for name, status in object.libraries.items %}
            <p>{{ name }} - <b>{{ status}}</b></p>
            {% endfor %}
          </div><br>
          <b>Command</b>
          <div class="col-offset-4 col-8">{{ object.command }}</div>
          <br>
          <a href="{% url 'jobs:create-container' object.job_id %}">create container</a>
          <br>
          <br><br>

          <h3>History</h3>
          <div class="col-9">
            <table class="table">
              <tbody>
                {% for cont in containers %}
                <tr>
                  <td><a href="{% url 'jobs:container-detail' cont.uid %}">{{cont.uid}}</a></td>
                  {% if cont.container_type == "2" %}
                    <td>S</td>
                  {% elif cont.container_type == "1" %}
                    <td>D</td>
                  {% endif %}
                  <td>{{ cont.created }}</td>
                  <td>{{ cont.status }}</td>
                </tr>
                {% empty %}
                  <td>No element's in the history</td>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <div class="col-3">
          </div>
        </div>
    </div>
</div>
{% endblock%}

templates/jobs/jobs_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Jobs</h1>
      <table class="table">
        <tbody>
          {% for job in object_list %}
            <tr>
              <td>{{job.job_id}}</a></td>
              <td><a href="{% url 'jobs:job-detail' job.job_id %}">info >></a></td>
              <td>{{job.libraries}}</a></td>
            </tr>
            {% empty %}
            <tr>
              <td>No jobs yet.</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock%}